module: Events
author: Matt Moriarity
author_url: https://www.mattmoriarity.com/
github_url: https://github.com/mjm/Events

swift_build_tool: spm
swift_version: '5.1'

theme: fullwidth

abstract: Documentation/Sections/*.md

custom_categories:
- name: Using Events
  children:
  - EventBuilder
  - Event

- name: Destinations
  children:
  - EventSink
  - OSLogEventSink